name: Denizen
authors: ['aufdemrand', 'mcmonkey']
version: ${project.version} (build ${BUILD_NUMBER})
main: net.aufdemrand.denizen.Denizen
softdepend: [Citizens, Vault]

commands:
  denizen:
    description: Lists denizen commands.
    usage: /denizen help
    permission: denizen.basic
  notable:
    description: Lists notable commands.
    usage: /notable help
    permission: denizen.notable
  dscript:
    description: Lists dScript commands.
    usage: /dScript help
    permission: denizen.dscript
  ex:
    description: Executes a dScript command.
    usage: Use /ex in front of a normal script entry.
    permission: denizen.ex


permissions:
  denizen.*:
    description: Gives access to Denizen commands
    default: op
    children:
      denizen.basic: true
      denizen.notable: true
      denizen.notable.basic: true
      denizen.dscript: true
      denizen.ex: true
      denizen.debug: true
      denizen.submit: true
      denizen.npc.health: true
      denizen.npc.sneak: true
      denizen.npc.effect: true
      denizen.npc.fish: true
      denizen.npc.sleep: true
      denizen.npc.stand: true
      denizen.npc.sit: true
      denizen.npc.nameplate: true
      denizen.npc.nickname: true
      denizen.npc.trigger: true
      denizen.npc.assign: true
      denizen.npc.constants: true
      denizen.npc.pushable: true
  denizen.npc.*:
    description: Gives access to the /npc commands added by Denizen
    default: op
    children:
      denizen.npc.health: true
      denizen.npc.sneak: true
      denizen.npc.effect: true
      denizen.npc.fish: true
      denizen.npc.sleep: true
      denizen.npc.stand: true
      denizen.npc.sit: true
      denizen.npc.nameplate: true
      denizen.npc.nickname: true
      denizen.npc.trigger: true
      denizen.npc.assign: true
      denizen.npc.constants: true
      denizen.npc.pushable: true
      
