package com.denizenscript.denizen.nms.v1_21;

public class ReflectionMappingsInfo {

    // Content generated by ReflectionMappingsGenerator - https://github.com/DenizenScript/ReflectionMappingsGenerator

    // net.minecraft.world.level.block.state.BlockBehaviour
    public static String BlockBehaviour_explosionResistance = "G";

    // net.minecraft.core.MappedRegistry
    public static String MappedRegistry_registrationInfos = "h";

    // net.minecraft.world.entity.Entity
    public static String Entity_onGround = "bc";
    public static String Entity_DATA_SHARED_FLAGS_ID = "aA";
    public static String Entity_DATA_CUSTOM_NAME = "bm";
    public static String Entity_DATA_CUSTOM_NAME_VISIBLE = "bn";

    // net.minecraft.world.entity.LivingEntity
    public static String LivingEntity_attackStrengthTicker = "bz";
    public static String LivingEntity_autoSpinAttackTicks = "bW";
    public static String LivingEntity_setLivingEntityFlag_method = "c";

    // net.minecraft.world.entity.player.Player
    public static String Player_DATA_PLAYER_ABSORPTION_ID = "b";

    // net.minecraft.server.level.ServerPlayer
    public static String ServerPlayer_respawnConfig = "dr";

    // net.minecraft.world.entity.monster.EnderMan
    public static String EnderMan_DATA_CREEPY = "cx";

    // net.minecraft.world.entity.monster.zombie.Zombie
    public static String Zombie_inWaterTime = "cL";

    // net.minecraft.world.item.Item
    public static String Item_components = "c";

    // net.minecraft.world.item.component.ResolvableProfile
    public static String ResolvableProfile_unpack_method = "a";

    // net.minecraft.world.item.component.ResolvableProfile$Partial
    public static String ResolvableProfilePartial_id = "d";

    // net.minecraft.world.level.Level
    public static String Level_isClientSide = "D";

    // net.minecraft.server.level.ThreadedLevelLightEngine
    public static String ThreadedLevelLightEngine_addTask_method = "a";

    // net.minecraft.server.level.ThreadedLevelLightEngine$TaskType
    public static String ThreadedLevelLightEngineTaskType_PRE_UPDATE = "a";

    // net.minecraft.world.entity.ExperienceOrb
    public static String ExperienceOrb_age = "k";

    // net.minecraft.world.entity.item.ItemEntity
    public static String ItemEntity_DATA_ITEM = "c";

    // net.minecraft.world.level.biome.Biome
    public static String Biome_climateSettings = "i";
    public static String Biome_attributes = "l";

    // net.minecraft.world.level.biome.BiomeSpecialEffects
    public static String BiomeSpecialEffects_foliageColorOverride = "c";

    // net.minecraft.network.Connection
    public static String Connection_receiving = "h";
    public static String Connection_packetListener = "n";

    // net.minecraft.server.network.ServerGamePacketListenerImpl
    public static String ServerGamePacketListenerImpl_aboveGroundTickCount = "L";
    public static String ServerGamePacketListenerImpl_aboveGroundVehicleTickCount = "N";
    public static String ServerGamePacketListenerImpl_awaitingPositionFromClient = "H";
    public static String ServerGamePacketListenerImpl_awaitingTeleport = "I";
    public static String ServerGamePacketListenerImpl_chunkSender = "h";

    // net.minecraft.server.network.ServerCommonPacketListenerImpl
    public static String ServerCommonPacketListenerImpl_connection = "e";
    public static String ServerCommonPacketListenerImpl_createCookie_method = "a";

    // net.minecraft.network.protocol.game.ClientboundPlayerAbilitiesPacket
    public static String ClientboundPlayerAbilitiesPacket_walkingSpeed = "k";

    // net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket
    public static String ClientboundSectionBlocksUpdatePacket_sectionPos = "c";
    public static String ClientboundSectionBlocksUpdatePacket_positions = "d";
    public static String ClientboundSectionBlocksUpdatePacket_states = "e";

    // net.minecraft.network.protocol.game.ClientboundMoveEntityPacket
    public static String ClientboundMoveEntityPacket_xa = "b";
    public static String ClientboundMoveEntityPacket_ya = "c";
    public static String ClientboundMoveEntityPacket_za = "d";
    public static String ClientboundMoveEntityPacket_yRot = "e";
    public static String ClientboundMoveEntityPacket_xRot = "f";

    // net.minecraft.network.protocol.game.ClientboundSetEntityMotionPacket
    public static String ClientboundSetEntityMotionPacket_id = "b";

    // net.minecraft.network.protocol.game.ClientboundSetPassengersPacket
    public static String ClientboundSetPassengersPacket_passengers = "c";

    // net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo
    public static String ClientboundLevelChunkPacketDataBlockEntityInfo_packedXZ = "c";
    public static String ClientboundLevelChunkPacketDataBlockEntityInfo_y = "d";

    // net.minecraft.network.syncher.SynchedEntityData
    public static String SynchedEntityData_itemsById = "e";

    // net.minecraft.world.entity.projectile.FishingHook
    public static String FishingHook_nibble = "j";
    public static String FishingHook_timeUntilLured = "k";
    public static String FishingHook_timeUntilHooked = "l";

    // net.minecraft.tags.TagNetworkSerialization$NetworkPayload
    public static String TagNetworkSerializationNetworkPayload_tags = "b";

    // net.minecraft.core.HolderSet$Named
    public static String HolderSetNamed_bind_method = "b";

    // net.minecraft.core.Holder$Reference
    public static String HolderReference_bindTags_method = "a";

    // net.minecraft.server.level.ServerLevel
    public static String ServerLevel_sleepStatus = "O";

    // net.minecraft.world.item.AdventureModePredicate
    public static String AdventureModePredicate_predicates = "g";

    // net.minecraft.stats.ServerRecipeBook
    public static String ServerRecipeBook_addHighlight_method = "e";
}
