package com.denizenscript.denizen.nms.v1_19;

public class ReflectionMappingsInfo {

    // Content generated by ReflectionMappingsGenerator - https://github.com/DenizenScript/ReflectionMappingsGenerator

    // net.minecraft.advancements.AdvancementList
    public static String AdvancementList_roots = "c";
    public static String AdvancementList_tasks = "d";

    // net.minecraft.world.level.block.state.BlockBehaviour
    public static String BlockBehaviour_explosionResistance = "aH";

    // net.minecraft.core.MappedRegistry
    public static String MappedRegistry_frozen = "l";

    // net.minecraft.world.item.crafting.RecipeManager
    public static String RecipeManager_byName = "d";

    // net.minecraft.world.entity.Entity
    public static String Entity_onGround = "N";
    public static String Entity_DATA_SHARED_FLAGS_ID = "an";
    public static String Entity_DATA_CUSTOM_NAME = "aR";
    public static String Entity_DATA_CUSTOM_NAME_VISIBLE = "aS";

    // net.minecraft.world.entity.LivingEntity
    public static String LivingEntity_attackStrengthTicker = "aO";
    public static String LivingEntity_autoSpinAttackTicks = "bx";
    public static String LivingEntity_setLivingEntityFlag_method = "c";

    // net.minecraft.world.entity.player.Player
    public static String Player_DATA_PLAYER_ABSORPTION_ID = "e";
    public static String Player_DATA_PLAYER_MODE_CUSTOMISATION = "bJ";

    // net.minecraft.server.level.ServerPlayer
    public static String ServerPlayer_respawnForced = "cP";

    // net.minecraft.world.entity.monster.EnderMan
    public static String EnderMan_DATA_CREEPY = "bU";

    // net.minecraft.world.entity.monster.Zombie
    public static String Zombie_inWaterTime = "cc";

    // net.minecraft.world.item.Item
    public static String Item_maxStackSize = "d";

    // net.minecraft.world.level.Level
    public static String Level_isClientSide = "B";

    // net.minecraft.server.level.ThreadedLevelLightEngine
    public static String ThreadedLevelLightEngine_addTask_method = "a";

    // net.minecraft.server.level.ThreadedLevelLightEngine$TaskType
    public static String ThreadedLevelLightEngineTaskType_PRE_UPDATE = "a";

    // net.minecraft.world.entity.item.ItemEntity
    public static String ItemEntity_DATA_ITEM = "c";

    // net.minecraft.world.level.biome.Biome
    public static String Biome_climateSettings = "i";

    // net.minecraft.world.level.biome.BiomeSpecialEffects
    public static String BiomeSpecialEffects_foliageColorOverride = "f";
    public static String BiomeSpecialEffects_fogColor = "b";
    public static String BiomeSpecialEffects_waterFogColor = "d";

    // net.minecraft.network.Connection
    public static String Connection_receiving = "k";

    // net.minecraft.server.network.ServerGamePacketListenerImpl
    public static String ServerGamePacketListenerImpl_aboveGroundTickCount = "H";
    public static String ServerGamePacketListenerImpl_aboveGroundVehicleTickCount = "J";
    public static String ServerGamePacketListenerImpl_connection = "h";
    public static String ServerGamePacketListenerImpl_awaitingPositionFromClient = "D";
    public static String ServerGamePacketListenerImpl_awaitingTeleport = "E";

    // net.minecraft.network.protocol.game.ClientboundPlayerAbilitiesPacket
    public static String ClientboundPlayerAbilitiesPacket_walkingSpeed = "j";

    // net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket
    public static String ClientboundSectionBlocksUpdatePacket_sectionPos = "b";
    public static String ClientboundSectionBlocksUpdatePacket_positions = "c";
    public static String ClientboundSectionBlocksUpdatePacket_states = "d";

    // net.minecraft.network.protocol.game.ClientboundMoveEntityPacket
    public static String ClientboundMoveEntityPacket_xa = "b";
    public static String ClientboundMoveEntityPacket_ya = "c";
    public static String ClientboundMoveEntityPacket_za = "d";
    public static String ClientboundMoveEntityPacket_yRot = "e";
    public static String ClientboundMoveEntityPacket_xRot = "f";

    // net.minecraft.network.protocol.game.ClientboundSetEntityMotionPacket
    public static String ClientboundSetEntityMotionPacket_id = "a";

    // net.minecraft.network.protocol.game.ClientboundTeleportEntityPacket
    public static String ClientboundTeleportEntityPacket_id = "a";
    public static String ClientboundTeleportEntityPacket_x = "b";
    public static String ClientboundTeleportEntityPacket_y = "c";
    public static String ClientboundTeleportEntityPacket_z = "d";
    public static String ClientboundTeleportEntityPacket_yRot = "e";
    public static String ClientboundTeleportEntityPacket_xRot = "f";

    // net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo
    public static String ClientboundLevelChunkPacketDataBlockEntityInfo_packedXZ = "a";
    public static String ClientboundLevelChunkPacketDataBlockEntityInfo_y = "b";

    // net.minecraft.world.entity.projectile.FishingHook
    public static String FishingHook_nibble = "j";
    public static String FishingHook_timeUntilLured = "k";
    public static String FishingHook_timeUntilHooked = "l";

    // net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase
    public static String BlockBehaviourBlockStateBase_getFluidState_method = "r";

    // net.minecraft.world.level.material.FluidState
    public static String FluidState_isRandomlyTicking_method = "f";
    public static String FluidState_isEmpty_method = "c";
    public static String FluidState_createLegacyBlock_method = "g";
    public static String FluidState_animateTick_method = "a";

    // net.minecraft.tags.TagNetworkSerialization$NetworkPayload
    public static String TagNetworkSerializationNetworkPayload_tags = "a";

    // net.minecraft.core.HolderSet$Named
    public static String HolderSetNamed_bind_method = "b";

    // net.minecraft.core.Holder$Reference
    public static String HolderReference_bindTags_method = "a";

    // net.minecraft.server.level.ServerLevel
    public static String ServerLevel_sleepStatus = "N";

}
